/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  docs: {
    Introduction: [
      'getting_started',
      'installation', 
      'querying', 
      'aggregations', 
      'instance_mapper', 
    ],   
    "API Reference": [
      'api',
    ],
    "API Modules": [
      "api/modules/_agg_",
      "api/modules/_cluster_",
      "api/modules/_compiler_",
      "api/modules/_document_",
      "api/modules/_expression_",
      "api/modules/_index_",
      "api/modules/_result_",
      "api/modules/_search_",
      "api/modules/_types_",
      "api/modules/_util_",
    ],
    "API Classes": [
      "api/classes/_agg_.aggexpression",
      "api/classes/_agg_.aggresult",
      "api/classes/_agg_.bucket",
      "api/classes/_agg_.bucketagg",
      "api/classes/_agg_.filter",
      "api/classes/_agg_.multibucketagg",
      "api/classes/_agg_.multibucketaggresult",
      "api/classes/_agg_.singlebucketagg",
      "api/classes/_agg_.singlebucketaggresult",
      "api/classes/_agg_.terms",
      "api/classes/_cluster_.cluster",
      "api/classes/_cluster_.esversion",
      "api/classes/_cluster_.index",
      "api/classes/_compiler_.compilervisitor",
      "api/classes/_document_.booleantype",
      "api/classes/_document_.datetype",
      "api/classes/_document_.doc",
      "api/classes/_document_.field",
      "api/classes/_document_.fieldtype",
      "api/classes/_document_.floattype",
      "api/classes/_document_.integertype",
      "api/classes/_document_.stringtype",
      "api/classes/_expression_.bool",
      "api/classes/_expression_.expression",
      "api/classes/_expression_.fieldexpression",
      "api/classes/_expression_.fieldqueryexpression",
      "api/classes/_expression_.literal",
      "api/classes/_expression_.params",
      "api/classes/_expression_.paramsexpression",
      "api/classes/_expression_.queryexpression",
      "api/classes/_expression_.rangeexpr",
      "api/classes/_expression_.sort",
      "api/classes/_expression_.source",
      "api/classes/_expression_.term",
      "api/classes/_expression_.terms",
      "api/classes/_result_.result",
      "api/classes/_result_.searchresult",
      "api/classes/_search_.searchquery",
      "api/classes/_search_.searchquerycontext",
      "api/classes/_agg_.aggexpression",
      "api/classes/_agg_.aggresult",
      "api/classes/_agg_.bucket",
      "api/classes/_agg_.bucketagg",
      "api/classes/_agg_.filter",
      "api/classes/_agg_.multibucketagg",
      "api/classes/_agg_.multibucketaggresult",
      "api/classes/_agg_.singlebucketagg",
      "api/classes/_agg_.singlebucketaggresult",
      "api/classes/_agg_.terms",
      "api/classes/_cluster_.cluster",
      "api/classes/_cluster_.esversion",
      "api/classes/_cluster_.index",
      "api/classes/_compiler_.compilervisitor",
      "api/classes/_document_.booleantype",
      "api/classes/_document_.datetype",
      "api/classes/_document_.doc",
      "api/classes/_document_.field",
      "api/classes/_document_.fieldtype",
      "api/classes/_document_.floattype",
      "api/classes/_document_.integertype",
      "api/classes/_document_.stringtype",
      "api/classes/_expression_.bool",
      "api/classes/_expression_.expression",
      "api/classes/_expression_.fieldexpression",
      "api/classes/_expression_.fieldqueryexpression",
      "api/classes/_expression_.literal",
      "api/classes/_expression_.params",
      "api/classes/_expression_.paramsexpression",
      "api/classes/_expression_.queryexpression",
      "api/classes/_expression_.rangeexpr",
      "api/classes/_expression_.sort",
      "api/classes/_expression_.source",
      "api/classes/_expression_.term",
      "api/classes/_expression_.terms",
      "api/classes/_result_.result",
      "api/classes/_result_.searchresult",
      "api/classes/_search_.searchquery",
      "api/classes/_search_.searchquerycontext"
    ],
    Changelog: [
      'changelog',
    ],
  },
};
